"""本机构建加速配置：生成/移除/查看 gitignored 的 `.cargo/config.local.toml`。

仓库 `.cargo/config.toml` 用 `include = [{ path = "config.local.toml", optional = true }]`
可选引入这份文件：不存在时没有任何影响，CI 与 GX 发布构建（干净检出）永远读不到它；
`scripts/gx_package.py` 在本文件存在时拒绝打包，避免把本机设置带进安装包。

默认内容（Windows 本机实测：小改动后的增量 dev 构建约快 12%，test 构建约快 5%）：
- Windows MSVC 目标改用 rust-lld 链接（比 link.exe 快；Linux x86_64 自 Rust 1.90 起已默认 lld）；
- 依赖不生成调试信息（`[profile.dev.package."*"] debug = false`，只影响 dev/test，herdr
  自身仍保留行号）。

`--parallel-frontend[=N]` 额外开启 rustc 并行前端（`-Zthreads=N`，默认 8）：通过
`RUSTC_BOOTSTRAP=1` 在 stable 编译器上启用不稳定选项。冷构建实测约快 44%，小改动的
增量构建没有收益。它不受 Rust 稳定性保证，个别版本可能 ICE；并且会让 anyhow、
proc-macro2、thiserror 的构建脚本切到 nightly 路径。开关变化会触发一次依赖全量重编；
出问题时去掉该选项重新 `--enable`，或 `--disable`。
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPO_CONFIG = PROJECT_ROOT / ".cargo" / "config.toml"
LOCAL_CONFIG = PROJECT_ROOT / ".cargo" / "config.local.toml"
MARKER = "# herdr local build config: generated by scripts/local_build_config.py"
DEFAULT_FRONTEND_THREADS = 8


class ConfigError(RuntimeError):
    pass


def host_triple(rustc: str = "rustc") -> str:
    try:
        verbose = subprocess.run(
            [rustc, "-vV"], capture_output=True, encoding="utf-8", errors="replace", check=True
        ).stdout
    except (OSError, subprocess.CalledProcessError) as error:
        raise ConfigError(f"无法从 `{rustc} -vV` 读取宿主 target：{error}") from error
    for line in verbose.splitlines():
        if line.startswith("host: "):
            return line.removeprefix("host: ").strip()
    raise ConfigError(f"`{rustc} -vV` 的输出里没有 host 行")


def render(host: str, frontend_threads: int | None = None) -> str:
    """生成配置文本；只有 Windows MSVC 宿主改链接器，并行前端对宿主 target 生效。"""
    lines = [
        MARKER,
        "# 只属于本机（gitignored）；由 .cargo/config.toml 的可选 include 引入。",
        "# 管理：just local-build-config --status / --enable [--parallel-frontend[=N]] / --disable",
        "",
    ]
    target_lines = []
    if host.endswith("-pc-windows-msvc"):
        target_lines.append('linker = "rust-lld"')
    if frontend_threads is not None:
        # 与仓库 config.toml 的 target rustflags（如 +crt-static）按数组拼接，不会互相覆盖。
        target_lines.append(f'rustflags = ["-Zthreads={frontend_threads}"]')
    if target_lines:
        lines += [f"[target.{host}]", *target_lines, ""]
    lines += ['[profile.dev.package."*"]', "debug = false", ""]
    if frontend_threads is not None:
        lines += ["[env]", 'RUSTC_BOOTSTRAP = "1"', ""]
    return "\n".join(lines)


def is_generated(path: Path) -> bool:
    try:
        return path.read_text(encoding="utf-8").startswith(MARKER)
    except OSError:
        return False


def repo_includes_local_config(repo_config: Path = REPO_CONFIG) -> bool:
    try:
        text = repo_config.read_text(encoding="utf-8")
    except OSError:
        return False
    return '"config.local.toml"' in text and "optional = true" in text


def enable(path: Path, content: str, force: bool = False) -> None:
    if path.exists() and not is_generated(path) and not force:
        raise ConfigError(f"{path} 不是本脚本生成的，拒绝覆盖（确认后加 --force）")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def disable(path: Path, force: bool = False) -> bool:
    if not path.exists():
        return False
    if not is_generated(path) and not force:
        raise ConfigError(f"{path} 不是本脚本生成的，拒绝删除（确认后加 --force）")
    path.unlink()
    return True


def _force_utf8_streams() -> None:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--enable", action="store_true", help="生成（或重写）本机配置")
    action.add_argument("--disable", action="store_true", help="删除本机配置")
    action.add_argument("--status", action="store_true", help="查看当前状态（默认）")
    parser.add_argument(
        "--parallel-frontend",
        nargs="?",
        type=int,
        const=DEFAULT_FRONTEND_THREADS,
        metavar="N",
        help=f"随 --enable 开启不稳定的并行前端 -Zthreads=N（默认 {DEFAULT_FRONTEND_THREADS}）",
    )
    parser.add_argument("--force", action="store_true", help="允许覆盖/删除非本脚本生成的文件")
    args = parser.parse_args(argv)
    _force_utf8_streams()
    if args.parallel_frontend is not None and not args.enable:
        parser.error("--parallel-frontend 只能与 --enable 一起使用")
    if args.parallel_frontend is not None and args.parallel_frontend < 2:
        parser.error("--parallel-frontend 的线程数至少为 2")
    if not repo_includes_local_config():
        print(f"error: {REPO_CONFIG} 没有可选引入 config.local.toml，本机配置不会生效", file=sys.stderr)
        return 2
    try:
        if args.enable:
            enable(LOCAL_CONFIG, render(host_triple(), args.parallel_frontend), force=args.force)
            print(f"已写入 {LOCAL_CONFIG}（下一次构建会整体重编一次）：")
            print(LOCAL_CONFIG.read_text(encoding="utf-8"))
            return 0
        if args.disable:
            removed = disable(LOCAL_CONFIG, force=args.force)
            print(f"已删除 {LOCAL_CONFIG}" if removed else f"{LOCAL_CONFIG} 不存在，无需删除")
            return 0
    except ConfigError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    if LOCAL_CONFIG.exists():
        origin = "本脚本生成" if is_generated(LOCAL_CONFIG) else "手工维护"
        print(f"已启用（{origin}）：{LOCAL_CONFIG}")
        print(LOCAL_CONFIG.read_text(encoding="utf-8"))
    else:
        print(f"未启用：{LOCAL_CONFIG} 不存在；`just local-build-config --enable` 生成")
    return 0


if __name__ == "__main__":
    sys.exit(main())
